version: "3.8"

services:
  database:
    container_name: breathing
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: brg
      MYSQL_DATABASE: breathing

  api:
    container_name: api
    image: dianus/apibrg
    links:
      - database
    build: ./
    volumes: 
      - ./:/app
    ports:
      - "8000:8000"
    devices: 
      - "/dev/ttyACM0:/dev/ttyACM0"

